#!/bin/bash
#This script sets the fairshare scores for labs.  Based on the 09/27/21 census with adjusted scores.

sacctmgr -i modify account set fairshare=120
sacctmgr -i modify account name=anderson_lab set fairshare=132
sacctmgr -i modify account name=arguelles_delgado_lab set fairshare=1020
sacctmgr -i modify account name=astrominger_lab set fairshare=440
sacctmgr -i modify account name=barak_lab set fairshare=325
sacctmgr -i modify account name=bfarrell_lab set fairshare=122
sacctmgr -i modify account name=bhi_lab set fairshare=440
sacctmgr -i modify account name=bloxham_lab set fairshare=560
sacctmgr -i modify account name=conroy_lab set fairshare=965
sacctmgr -i modify account name=cox_lab set fairshare=296
sacctmgr -i modify account name=davies_lab set fairshare=928
sacctmgr -i modify account name=de_mink_lab set fairshare=657
sacctmgr -i modify account name=denolle_lab set fairshare=150
sacctmgr -i modify account name=desai_lab set fairshare=312
sacctmgr -i modify account name=doeleman_lab set fairshare=440
sacctmgr -i modify account name=doshi-velez_lab set fairshare=222
sacctmgr -i modify account name=dsouza_lab set fairshare=178
sacctmgr -i modify account name=dvorkin_lab set fairshare=171
sacctmgr -i modify account name=eddy_lab set fairshare=1558
sacctmgr -i modify account name=edwards_lab set fairshare=216
sacctmgr -i modify account name=eisenstein_lab set fairshare=197
sacctmgr -i modify account name=finkbeiner_lab set fairshare=454
sacctmgr -i modify account name=fischer_lab set fairshare=184
sacctmgr -i modify account name=friend_lab set fairshare=216
sacctmgr -i modify account name=giribet_lab set fairshare=216
sacctmgr -i modify account name=guenette_lab set fairshare=325
sacctmgr -i modify account name=hernquist_external set fairshare=50
sacctmgr -i modify account name=hernquist_lab set fairshare=606
sacctmgr -i modify account name=hills_lab set fairshare=312
sacctmgr -i modify account name=hoekstra_lab set fairshare=325
sacctmgr -i modify account name=holman_lab set fairshare=197
sacctmgr -i modify account name=huttenhower_lab set fairshare=216
sacctmgr -i modify account name=huybers_lab set fairshare=230
sacctmgr -i modify account name=icecube set fairshare=512
sacctmgr -i modify account name=idreos_lab set fairshare=505
sacctmgr -i modify account name=informatics set fairshare=635
sacctmgr -i modify account name=ishii_lab set fairshare=222
sacctmgr -i modify account name=itc_lab set fairshare=197
sacctmgr -i modify account name=jacob_lab set fairshare=619
sacctmgr -i modify account name=jacobsen_lab set fairshare=206
sacctmgr -i modify account name=janson_lab set fairshare=555
sacctmgr -i modify account name=jjohnson_lab set fairshare=197
sacctmgr -i modify account name=jshapiro_lab set fairshare=216
sacctmgr -i modify account name=kaxiras_lab set fairshare=512
sacctmgr -i modify account name=ke_lab set fairshare=248
sacctmgr -i modify account name=keith_lab_seas set fairshare=210
sacctmgr -i modify account name=koumoutsakos_lab set fairshare=1320
sacctmgr -i modify account name=kovac_lab set fairshare=1061
sacctmgr -i modify account name=kozinsky_lab set fairshare=3401
sacctmgr -i modify account name=kuang_lab set fairshare=1478
sacctmgr -i modify account name=kubzansky_lab set fairshare=133
sacctmgr -i modify account name=legewie_lab set fairshare=146
sacctmgr -i modify account name=lichtman_lab set fairshare=712
sacctmgr -i modify account name=linz_lab set fairshare=2136
sacctmgr -i modify account name=loeb_lab set fairshare=517
sacctmgr -i modify account name=lopez_morales_lab set fairshare=197
sacctmgr -i modify account name=lukin_lab set fairshare=216
sacctmgr -i modify account name=martin_lab_seas set fairshare=132
sacctmgr -i modify account name=mazur_lab_seas set fairshare=134
sacctmgr -i modify account name=mccoll_lab set fairshare=1144
sacctmgr -i modify account name=mcelroy_lab set fairshare=132
sacctmgr -i modify account name=meade_lab set fairshare=2080
sacctmgr -i modify account name=meissner_lab set fairshare=132
sacctmgr -i modify account name=mitrovica_lab set fairshare=222
sacctmgr -i modify account name=moorcroft_lab set fairshare=806
sacctmgr -i modify account name=murphy_lab set fairshare=222
sacctmgr -i modify account name=narayan_lab set fairshare=1050
sacctmgr -i modify account name=nguyen_lab set fairshare=216
sacctmgr -i modify account name=ni_lab set fairshare=146
sacctmgr -i modify account name=oberg_lab set fairshare=197
sacctmgr -i modify account name=olveczky_lab set fairshare=538
sacctmgr -i modify account name=ortegahernandez_lab set fairshare=408
sacctmgr -i modify account name=parkes_lab set fairshare=505
sacctmgr -i modify account name=pehlevan_lab set fairshare=2304
sacctmgr -i modify account name=pfister_lab set fairshare=1561
sacctmgr -i modify account name=rush_lab set fairshare=156
sacctmgr -i modify account name=sabeti_lab set fairshare=353
sacctmgr -i modify account name=sasselov_lab set fairshare=197
sacctmgr -i modify account name=schrag_lab set fairshare=230
sacctmgr -i modify account name=shakhnovich_lab set fairshare=274
sacctmgr -i modify account name=sompolinsky_lab set fairshare=468
sacctmgr -i modify account name=stubbs_lab set fairshare=197
sacctmgr -i modify account name=sunderland_lab set fairshare=171
sacctmgr -i modify account name=tambe_lab set fairshare=1082
sacctmgr -i modify account name=tata_parkes_tamer set fairshare=158
sacctmgr -i modify account name=tata_yu_rush set fairshare=158
sacctmgr -i modify account name=tziperman_lab set fairshare=150
sacctmgr -i modify account name=viegas_lab set fairshare=360
sacctmgr -i modify account name=vishwanath_lab set fairshare=216
sacctmgr -i modify account name=wattenberg_lab set fairshare=360
sacctmgr -i modify account name=whipple_lab set fairshare=408
sacctmgr -i modify account name=wofsy_lab set fairshare=718
sacctmgr -i modify account name=wordsworth_lab set fairshare=939
sacctmgr -i modify account name=wunsch_lab set fairshare=132
sacctmgr -i modify account name=xchen_lab set fairshare=197
sacctmgr -i modify account name=xlin set fairshare=629
sacctmgr -i modify account name=yao_lab set fairshare=600
sacctmgr -i modify account name=yau2_lab set fairshare=440
sacctmgr -i modify account name=yin_lab set fairshare=312
sacctmgr -i modify account name=zhuang_lab set fairshare=448
sacctmgr -i modify account name=zickler_lab set fairshare=137
sacctmgr -i modify account name=zon_lab set fairshare=216
