#!/bin/bash
#This script sets the fairshare scores for labs.  Based on the 09/5/19 census with adjusted scores.

sacctmgr -i modify account set fairshare=100
sacctmgr -i modify account name=adair_hbs_lab set fairshare=126
sacctmgr -i modify account name=anderson_lab set fairshare=112
sacctmgr -i modify account name=anl set fairshare=168
sacctmgr -i modify account name=arguelles_delgado_lab set fairshare=1000
sacctmgr -i modify account name=astrominger_lab set fairshare=420
sacctmgr -i modify account name=barak_lab set fairshare=501
sacctmgr -i modify account name=betley_lab set fairshare=106
sacctmgr -i modify account name=bfarrell_lab set fairshare=112
sacctmgr -i modify account name=bhi_lab set fairshare=420
sacctmgr -i modify account name=bloxham_lab set fairshare=540
sacctmgr -i modify account name=cnl set fairshare=504
sacctmgr -i modify account name=conroy_lab set fairshare=612
sacctmgr -i modify account name=cox_lab set fairshare=276
sacctmgr -i modify account name=davies_lab set fairshare=908
sacctmgr -i modify account name=davis_lab set fairshare=111
sacctmgr -i modify account name=de_mink_lab set fairshare=637
sacctmgr -i modify account name=denolle_lab set fairshare=130
sacctmgr -i modify account name=desai_lab set fairshare=305
sacctmgr -i modify account name=doeleman_lab set fairshare=420
sacctmgr -i modify account name=doshi-velez_lab set fairshare=202
sacctmgr -i modify account name=dsouza_lab set fairshare=158
sacctmgr -i modify account name=dvorkin_lab set fairshare=151
sacctmgr -i modify account name=eddy_lab set fairshare=1282
sacctmgr -i modify account name=edwards_lab set fairshare=196
sacctmgr -i modify account name=eisenstein_lab set fairshare=177
sacctmgr -i modify account name=finkbeiner_lab set fairshare=177
sacctmgr -i modify account name=fischer_lab set fairshare=164
sacctmgr -i modify account name=friend_lab set fairshare=196
sacctmgr -i modify account name=gershman_lab set fairshare=168
sacctmgr -i modify account name=girguis_lab set fairshare=125
sacctmgr -i modify account name=giribet_lab set fairshare=241
sacctmgr -i modify account name=guenette_lab set fairshare=305
sacctmgr -i modify account name=hbs_rcs set fairshare=126
sacctmgr -i modify account name=hernquist_external set fairshare=50
sacctmgr -i modify account name=hernquist_lab set fairshare=586
sacctmgr -i modify account name=hoekstra_lab set fairshare=305
sacctmgr -i modify account name=holman_lab set fairshare=177
sacctmgr -i modify account name=hsph_bioinfo set fairshare=168
sacctmgr -i modify account name=hsph_users set fairshare=168
sacctmgr -i modify account name=huttenhower_lab set fairshare=264
sacctmgr -i modify account name=huybers_lab set fairshare=210
sacctmgr -i modify account name=icecube set fairshare=512
sacctmgr -i modify account name=idreos_lab set fairshare=485
sacctmgr -i modify account name=informatics set fairshare=615
sacctmgr -i modify account name=ishii_lab set fairshare=202
sacctmgr -i modify account name=israeli_hbs_lab set fairshare=106
sacctmgr -i modify account name=itc_lab set fairshare=177
sacctmgr -i modify account name=jacob_lab set fairshare=599
sacctmgr -i modify account name=jacobsen_lab set fairshare=186
sacctmgr -i modify account name=janson_lab set fairshare=535
sacctmgr -i modify account name=jjohnson_lab set fairshare=177
sacctmgr -i modify account name=jkrieger_hbs_lab set fairshare=106
sacctmgr -i modify account name=jschreger_hbs_lab set fairshare=102
sacctmgr -i modify account name=kaxiras_lab set fairshare=492
sacctmgr -i modify account name=ke_lab set fairshare=228
sacctmgr -i modify account name=keith_lab_seas set fairshare=190
sacctmgr -i modify account name=kferreira_lab set fairshare=106
sacctmgr -i modify account name=kovac_lab set fairshare=1041
sacctmgr -i modify account name=kozinsky_lab set fairshare=964
sacctmgr -i modify account name=kuang_lab set fairshare=1458
sacctmgr -i modify account name=kubzansky_lab set fairshare=113
sacctmgr -i modify account name=legewie_lab set fairshare=126
sacctmgr -i modify account name=lichtman_lab set fairshare=212
sacctmgr -i modify account name=linz_lab set fairshare=2116
sacctmgr -i modify account name=loeb_lab set fairshare=497
sacctmgr -i modify account name=lopez_morales_lab set fairshare=177
sacctmgr -i modify account name=luk_lab set fairshare=168
sacctmgr -i modify account name=lukin_lab set fairshare=196
sacctmgr -i modify account name=martin_lab_seas set fairshare=112
sacctmgr -i modify account name=mazur_lab_seas set fairshare=114
sacctmgr -i modify account name=mccoll_lab set fairshare=1124
sacctmgr -i modify account name=mcelroy_lab set fairshare=112
sacctmgr -i modify account name=mcl set fairshare=302
sacctmgr -i modify account name=meade_lab set fairshare=2060
sacctmgr -i modify account name=meissner_lab set fairshare=113
sacctmgr -i modify account name=mitrovica_lab set fairshare=202
sacctmgr -i modify account name=moorcroft_lab set fairshare=112
sacctmgr -i modify account name=murphy_lab set fairshare=202
sacctmgr -i modify account name=narayan_lab set fairshare=1030
sacctmgr -i modify account name=ncf_users set fairshare=168
sacctmgr -i modify account name=nguyen_lab set fairshare=264
sacctmgr -i modify account name=ni_lab set fairshare=126
sacctmgr -i modify account name=nicholas_hbs_lab set fairshare=106
sacctmgr -i modify account name=nrg set fairshare=168
sacctmgr -i modify account name=oberg_lab set fairshare=177
sacctmgr -i modify account name=olveczky_lab set fairshare=518
sacctmgr -i modify account name=ortegahernandez_lab set fairshare=388
sacctmgr -i modify account name=parkes_lab set fairshare=485
sacctmgr -i modify account name=pascual-leone set fairshare=168
sacctmgr -i modify account name=pehlevan_lab set fairshare=2284
sacctmgr -i modify account name=pierce_lab set fairshare=113
sacctmgr -i modify account name=rush_lab set fairshare=136
sacctmgr -i modify account name=sabeti_lab set fairshare=333
sacctmgr -i modify account name=sasselov_lab set fairshare=177
sacctmgr -i modify account name=schrag_lab set fairshare=210
sacctmgr -i modify account name=scn set fairshare=168
sacctmgr -i modify account name=seage_lab set fairshare=168
sacctmgr -i modify account name=seas_iacs set fairshare=106
sacctmgr -i modify account name=shakhnovich_lab set fairshare=1954
sacctmgr -i modify account name=slurm_group_hbs_l3 set fairshare=106
sacctmgr -i modify account name=sompolinsky_lab set fairshare=448
sacctmgr -i modify account name=spierce_lab set fairshare=126
sacctmgr -i modify account name=stubbs_lab set fairshare=177
sacctmgr -i modify account name=sunderland_lab set fairshare=151
sacctmgr -i modify account name=tambe_lab set fairshare=1062
sacctmgr -i modify account name=tata_parkes_tamer set fairshare=138
sacctmgr -i modify account name=tata_yu_rush set fairshare=138
sacctmgr -i modify account name=tziperman_lab set fairshare=130
sacctmgr -i modify account name=vcn set fairshare=168
sacctmgr -i modify account name=vishwanath_lab set fairshare=196
sacctmgr -i modify account name=vsl set fairshare=168
sacctmgr -i modify account name=whipple_lab set fairshare=388
sacctmgr -i modify account name=wofsy_lab set fairshare=133
sacctmgr -i modify account name=wordsworth_lab set fairshare=919
sacctmgr -i modify account name=wunsch_lab set fairshare=112
sacctmgr -i modify account name=xchen_lab set fairshare=177
sacctmgr -i modify account name=xie_lab set fairshare=106
sacctmgr -i modify account name=xlin set fairshare=417
sacctmgr -i modify account name=yau2_lab set fairshare=420
sacctmgr -i modify account name=yin_lab set fairshare=279
sacctmgr -i modify account name=ysinger_group set fairshare=408
sacctmgr -i modify account name=zhuang_lab set fairshare=428
sacctmgr -i modify account name=zickler_lab set fairshare=117
sacctmgr -i modify account name=zon_lab set fairshare=196
